version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      # Schedule on 29 Feb to mostly disable automatic runs (intention:
      # Dependabot should only be run manually)
      cronjob: "0 0 29 2 *"
